import type { Metadata } from 'next';
import { Kumbh_Sans } from 'next/font/google';
import './globals.css';

const kumbh_sans = Kumbh_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Jobs Board',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumbh_sans.className}>{children}</body>
    </html>
  );
}
